### ISSUE TITLE
Fine Electronics unlocks soil -> sand recipe

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#100]
Mods: CP, FE, Industry

That recipe feels out of place. Maybe it could go in Filtration, Separation, or Wood Processing 2?

**Comment by kingarthur91** [comment]
unknown currently. need to decide and put the washer somewhere as well

**Comment by Havvy** [comment]
Filtration has pure sand from sand as well, so wherever soil to sand ends up, that one should also be with it.

I continue to be a proponent of lots of technologies that each do one thing and one thing well, so I'd argue putting those two together with a requirement of logistic science + separation named "Soil Washing" or something.

**Comment by kingarthur91** [comment]
moved sand to filtration. i see no need to create a tech just for this as its unnecessary bloat
