### ISSUE TITLE
Cooling tower 2 does not depend on Cooling Tower 1

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#101]
Mods: CP, FE, Industry

**Comment by ShadowGlass0** [comment]
Mods: PyCoal

Cooling Tower 2 also has missing prerequisites (required for the recipe):
- Concrete
- Engine (for Pump)
- Fluid Handling (for Storage tank) - It might make more sense to make Fluid Handling a prerequisite for Energy Generation 1. It's not a strict requirement, but you're dealing with a lot of fluids, and it would take care of any later requirements like this.

**Comment by kingarthur91** [comment]
see #118 on this as well
