### ISSUE TITLE
Olefin Plant

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#102]
Mods: CP, FE, Industry

The Lubricant tech unlocks the olefin plant, which is used to make lubricant. However lube requires olefins, which is requires Coal processing 2, so Lubricant should depend on CP2.
Additionally, Fuel Production tech unlocks several recipes for the olefin plant, so it should depend on Lubricant.

**Comment by ShadowGlass0** [comment]
Lubricant is already dependent on CP2 through Mukmoux. Fixing the Fuel Production.
