### ISSUE TITLE
Coal Processing 2 + py Industry

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#104]
Mods: CP, FE, Industry

Coal Processing 2 adds Niobium pipes and Nexelit accumulators, however it does not depend on Niobium, and Chemical Science Pack technologies which unlock both of those.

**Comment by ShadowGlass0** [comment]
That's tricky. Niobium is Logistic science in PyCoal only, and it's after Coal Processing 2.

**Comment by ShadowGlass0** [comment]
Sorry, misclick

**Comment by ShadowGlass0** [comment]
[Moved to pyindustry](https://github.com/pyanodon/pyindustry/issues/17#issue-947353859)
