### ISSUE TITLE
Excavation 1 should require Niobium

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#105]
Mods: CP, FE, Industry

Excavation 1 unlock Sand Extractors which require Niobium. It also unlocks a few recipes that use drill heads, also unlocked by Niobium. If Coal processing 2 depended on Niobium then it would solve this.

**Comment by ShadowGlass0** [comment]
Issue exists in PyCoal only too, but we should be able to just add Niobium as a prereq for Excavation 1 (and remove Coal Processing 2). Coal Processing 2 doesn't need Niobium
