### ISSUE TITLE
Desulfurisation & Oil extraction techs

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#109]
mods: PyCoal

(ignoring the active carbon -> syngas recipe, it was already mentioned elsewhere)

Missing prerequisites for Desulfurisation tech:
- Coal processing 2: Desulfurisatior unit requires chemical plant

Oil extraction tech has the Heavy oil recipe which requires Desulfurisation unit, Solid fuel recipe, which requires chemical plant, and Plastic recipe, which requires petgas.

Recipes between these two techs should be rearranged, possibly even merging the techs. The only available oil processing from crude is desulfurisation in PyCoal, so one doesn't make sense without the other.

**Comment by ShadowGlass0** [comment]
Crude oil can also be used for Flamethrower ammo, and as fuel for Flamethrower turrets, so that could be a reason to keep them as separate techs.

**Comment by ShadowGlass0** [comment]
Oil extraction should have a dependency on Logistic science pack

**Comment by kingarthur91** [comment]
@ShadowGlass0 please give this a second look that all issues are resolved with this. ignore heavy oil solid fuel as ill deal with it when i deal with the rest.

**Comment by ShadowGlass0** [comment]
Heavy oil is still in a weird place. There's the heavy oil -> solid fuel recipe still in Oil Extraction, with no heavy oil dependencies. Could be moved maybe to Fuel Production.

Some other notes:

Right now all 3 vanilla oil products (heavy, light oil, petgas) can be produced from PyCoal sources around green science. 
- Heavy oil from oleochemicals at Advanced separation
- Light oil from Syngas at Coal processing 2
- Petgas from RefSyngas at Coal processing 2
- Petgas from Organic solvent + Olefins at Advanced separation (Olefins at that stage is only available as a byproduct of Syngas->Light oil)

Vanilla oil mining + desulfurization is at Chem science, so that's the advanced production for these now. Is this all intended?

**Comment by kingarthur91** [comment]
I'm removing solid fuel completely so no on the heavy oil. 

On the rest yes that's what I'm intending to go with for pycp. Vanilla oil processing is later game and is going to be finite. Unless you find a way to make unlimited oil. @

**Comment by kingarthur91** [comment]
There is currently a few crude oil producing recipes in placeholder that still need to find a home somewhere.

**Comment by ShadowGlass0** [comment]
OK
