### ISSUE TITLE
Lubricant prerequisites

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#112]
mods: PyCoal
tech: Lubricant

Missing prerequisite:
- Fluid handling (storage tank for Olefin plant)

As mentioned [here](https://github.com/pyanodon/pycoalprocessing/issues/101#issuecomment-882276255), if Energy Generation 1 would have a dependency on Fluid handling, that would solve this issue as well.

**Comment by kingarthur91** [comment]
see #118 for fluid handling situation. i think doing that would also fix this 1.

**Comment by ShadowGlass0** [comment]
Will be fixed with #118
