### ISSUE TITLE
Burner Prereq

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#114]
mods: PyCoal
tech: Burner

Missing prerequisite:

Advanced Material Processing (needed for steel furnace)
Advanced Material Processing requires green science but this tech requires only red.

**Comment by kingarthur91** [comment]
i dont think this is a pycoal tech. pyindustries maybe?

**Comment by wesdotcool** [comment]
Ah yes. I'll move it
