### ISSUE TITLE
Concrete

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#117]
Mods: PyCoal
Tech: Concrete

The new concrete recipe requires sulfuric acid which isn't available until Sulfur processing. Additionally, the new recipe is much more expensive compared to the vanilla recipe which still exists.

**Comment by ShadowGlass0** [comment]
Concrete tech has missing prerequisite to Logistic science pack.

The only source of Limestone seems to be Soil separation (20 soil -> 2 limestone + junk). This makes concrete pretty expensive. I think the amount of lime needed can be reduced quite a bit.

The rich clay is similarly annoying. Maybe you could add a second concrete recipe with lime+sand+gravel+water, which is the [IRL recipe](https://www.wikihow.com/Make-Concrete) for the most part.

**Comment by kingarthur91** [comment]
Theres already a second recipe with boric acid
