### ISSUE TITLE
Advanced oil processing

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#121]
mods: PyCoal

Advanced oil processing is behind the Chemical science pack tech, but it only requires Logistic science.

Coal processing 2 dependency would make more sense, if it stays Logi science only.

**Comment by kingarthur91** [comment]
im still undecided about advanced oil processing. probably going to kill the tech in pycoal and move or remove the recipes as needed.

**Comment by kingarthur91** [comment]
removed advanced oil processing and solid fuel items
