### ISSUE TITLE
Split Electric Energy Distribution 1 into Two Researches

### ISSUE THREAD

**Issue by Havvy** [pyanodon/pycoalprocessing#136]
The medium electric pole and large electric poles requires completely different classes of ingredients, and could each be in their own technology. If you're feeling generous, the medium electric pole could actually be unlocked right after Coal Processing1, but perhaps making it unlockable right after logistic science would be okay. The large electric pole can continue to be locked behind niobium.

**Comment by kingarthur91** [comment]
took a look at this and i ended up making some changes that renders this unnecessary.
