### ISSUE TITLE
Move Aromatics from Cresote to Coal Processing 1

### ISSUE THREAD

**Issue by Havvy** [pyanodon/pycoalprocessing#137]
I'm told this is already done.

There's a recipe in Separation that gets aromatics from creosote. It feels weird in there because it's the only liquid when the rest are about separating soils and sands. As such, if the aromatics from creosote recipes gets moved to Coal Processing 1, the separation technology becomes optional until logistics science (though still really really useful) and separation gets removed as a dependency on plastics.

**Comment by kingarthur91** [comment]
done
