### ISSUE TITLE
Move niobium-iron alloy to Niobium Tech

### ISSUE THREAD

**Issue by Havvy** [pyanodon/pycoalprocessing#138]
The alloy is useful for two main things with just PyCP:

* Making optical wire for chemical science
* Making red belts

Currently, it is in "Fine Electronics" for its first usage, but that requires that "Logistics 2" is locked behind "Fine Electronics". If, instead, the alloy is unlocked with "Niobium" directly, then both "Fine Electronics" and "Logistics 2" can be locked behind "Niobium", making the chain for "Logistics 2" slightly shorter.

**Comment by kingarthur91** [comment]
also done
