### ISSUE TITLE
Acetylene Technology

### ISSUE THREAD

**Issue by Havvy** [pyanodon/pycoalprocessing#147]
# Current Status

With just Py Coal Processing, acetylene is locked behind filtration 2 as it seems to just be an alternative recipe for getting slaked lime with acetylene as a by-product to be turned into combustion fluid and burned for energy. It's currently extremely advantageous to do so, giving slightly less than 1GJ of power per 100 slaked lime created to the point that it actually looks like a really good option for fuel. The acetylene stuff (including lime) then gets moved to coal processing 1 with Py Raw Ores.

# Technology Change Suggestions

Acetylene should be its own technology. Without Py Raw Ores, it can be in the Energy Generation lines, either after production science effectively acting as "Energy Generation 4" or perhaps after energy generation 2 with a lot less energy given. With Raw Ores, it could depend upon Coal Processing 1 since it needs the gassifier and then lead and titanium processing 1 can depend upon it.

**Comment by kingarthur91** [comment]
i dont want to add a rather unnecessary tech for acetylene given it has no real use. ive disabled it in pycoal and added an unlock for it in pyfusion where its needed. im leaving the combustion recipe disabled
