### ISSUE TITLE
Fuel production prerequisites

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#162]
mods: PyCoal
tech: Fuel production

Redundant prerequisites:
- Chemical science pack (already required for Desulfurisation)

This tech is pretty big (16 recipes). A separate Olefins technology could be created and the Olefins related stuff moved there (about half the recipes). Can be at Logistic or Chemical science.

**Comment by kingarthur91** [comment]
fuel production has a serious case of coal processing disease and needs cleared out and cleaned up. we need to look at what should actually be in it and then see if the rest fit or need moved

**Comment by kingarthur91** [comment]
recipes have been moved around and i think this is fixed now and the tech name has been tweaked to better indicate what it does
