### ISSUE TITLE
Production science pack prerequisites

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#163]
mods: PyCoal
tech: Production science pack

Missing prerequisites:

Redundant prerequisites:
- Filtration 2 (already required for Energy generation 3)
- ? Robotics: Probably a left over from vanilla, when the science pack required flying robot frames. It's not any more, so it can be removed.

**Comment by kingarthur91** [comment]
i added robotics. idk why now. probably was going to use it at first and changed it later and forgot to fix the techs. will fix
