### ISSUE TITLE
Muddy Sludge

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#185]
- Many recipes that used to give tailings now give muddy sludge. The only use for muddy sludge is logs. It seems like there will be far more muddy sludge than needed. There should be another recipe to effectively void muddy sludge
  - sludge to fertilizer. Maybe with manure and other reagents
  - sludge to soil
  - sludge to stone
  - sludge to trace amounts of ores, like quenching
- It has the same icon as tailings. This will cause massive confusion

**Comment by kingarthur91** [comment]
ive added a few uses for muddy sludge. feretilizer doesnt exist till pyhightech/pyalienlife so thats not an option in this mod. i dont want to add options to convert it into soil or stone as itll just create a loop with no real purpose besides to be a void recipe that isnt actually a void recipe. quenching already isnt very good i dont wanna add more like it that arent worth using.

**Comment by oorzkws** [comment]
There's quite a few uses for muddy sludge now, most of them are somewhat useful. Tailings is somewhat hard to get early on, but it's not awful (and there should be *some* difficulty).
