### ISSUE TITLE
Gun turret tech

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#199]
Gun turret is sort of orphan tech now, with no connection to the tech tree. Should we make it a prerequisite to Military science pack or Military 2 (same as the Wall)? Technically it's not required as an ingredient for anything, but not all dependencies need to be based on ingredients.

**Comment by kingarthur91** [comment]
id say make it a dependent of mil 1 tech for now. might need to double check if it pushes them to far back for biters

**Comment by ShadowGlass0** [comment]
I meant the other way around. Make gun turret a prerequisite to something. Like Wall is a prerequisite to Military science pack.

**Comment by kingarthur91** [comment]
That works as well. Ethier way I think is probably good to connect it
