### ISSUE TITLE
Desulfurisation localization 

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#211]
My spell check always wants to correct this to Desulfurization with a 'z'. It's not my area of expertise, I just thought I'd mention it.

**Comment by ShadowGlass0** [comment]
The Desulfurisator unit (both item & entity) should also be changed the same way for consistency.

**Comment by kingarthur91** [comment]
@ShadowGlass0 please double check weve gotten them all now. searching for "desulfuris" no longer gives me any hits in any of the mods
