### ISSUE TITLE
glass-2 prerequisites

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#214]
Mods: PyCoal

glass-2 recipe is currently in Separation (red science), but it needs Fine sand (unlocked at Filtration) and Powdered quartz (unlocked at Crusher), and both of those are green science techs.
Filtration & Crusher are not dependent on each other right now. 

Suggestion:
- Quartz processing tech, with both the Powdered quartz and glass-2 recipes, dependent on Crusher (green science).
- The above will be green science, so we won't be able to do anything with crushed quartz at red science. Make the above Quartz processing 2, and add Quartz processing 1 tech, with a Molten glass recipe using crushed quartz, dependent on Separation (red science). 

Note: In PyRO the glass-2 recipe is using crushed quartz, and glass-3 is the Powdered quartz + Fine sand, so we'd just go back to the same recipes as PyRO.

Alternative: Remove the Powdered quartz, and use only Crushed quartz at red science with the PyRO glass-2 recipe. I've checked and to make 1 of each science pack, you need 20.5 molten glass in total, with PyCoal only. With the powdered quartz recipe, that's only 0.82 Powdered quartz, so it might  not be necessary. But I haven't checked the glass usage with PyFE or especially with PyHT.

**Comment by kingarthur91** [comment]
ive moved glass 2 to advanced material processing and added the filtration tech. i think the rich dust/crushed quartz recipe can be moved up into green tech somewhere
