### ISSUE TITLE
Coal gas to Syngas Recipe prod mod inconsistent

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#230]
Coal gas -> syngas recipe allows productivity modules, however the "upgraded" version of the recipe coal gas + O2 -> syngas does not allow prod mods. This means with high level buildings and prod mods, the recipe without O2 is more productive. These recipes should probably be consistent.

**Comment by kingarthur91** [comment]
i believe this has been fixed
