### ISSUE TITLE
Add circuit connections to mines

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#237]
List if Py mines:

- pyalienlife: collector, harvester
- pycoalprocessing: borax-mine(mk1-4), niobium-mine
- pyfusionenergy: diamond-mine, mo-mine, regolite-mine
- pyhightech: phosphate-mine, rare-earth-mine
- pypetroleumhandling: bitumen-seep-(mk1-4), natural-gas-extractor-(mk1-4), natural-gas-seep-(mk1-4), oil-derrick-(mk1-4), oil-sand-extractor-(mk1-4), sulfur-mine, tar-extractor-(mk1-4), tar-seep-(mk1-4)
- pyrawores: aluminium-mine, chromium-mine, coal-mine, copper-mine, iron-mine, lead-mine, nexelit-mine, nickel-mine, phosphate-mine-02, quartz-mine, salt-mine, tin-mine, titanium-mine, uranium-mine, zinc-mine
- pyalternativeenergy: antimonium-drill-(mk1-4), geothermal-plant-mk01, ree-mining-drill-(mk1-4)

Some of the pypetroleumhandling mines are only placed by script normally, so it might be difficult to test.

**Comment by JStMorgan** [comment]
Updating here for my own convenience:

**PyAL**

- [ ] Collector (all Mks.)
- [ ] Harvester

**PyCP**

- [ ] Fluid Mining Drill (all Mks.)
- [ ] Crystal Mine (all Mks.)
- [ ] Niobium Mine

**PyFE**

- [ ] Diamond Mine
- [ ] Molybdenum Mine
- [ ] Regolite Mine

**PyHT**

- [ ] Phosphate Mine (regular)
- [ ] Rare-Earth Extractor (large)

**PyPH**

- [ ] Small Oil Derrick (all Mks.)
- [ ] Tar Extractor (all Mks.)
- [ ] Natural Gas Derrick (all Mks.)
- [ ] Oil Sands Extractor (all Mks.)
- [ ] Sulphur Mine

**PyRO**

- [ ] Aluminium Mine
- [ ] Chromium Mine
- [ ] Coal Mine
- [ ] Copper Mine
- [ ] Iron Mine
- [ ] Lead Mine
- [ ] Nexelit Mine
- [ ] Nickel Mine
- [ ] Phosphate Mine (big)
- [ ] Quartz Mine
- [ ] Salt Mine
- [ ] Tin Mine
- [ ] Titanium Mine
- [ ] Uranium Mine
- [ ] Zinc Mine

**PyAE**

- [ ] Antimony Drill (all Mks.)
- [ ] Geothermal Plant
- [ ] Rare Earth Mining Drill (all Mks.)

**Comment by notnotmelon** [comment]
@JStMorgan I've moved this issue into the centralized py bug reports repo. Additionally, I believe uranium mines are now completed.

https://github.com/pyanodon/pybugreports/issues/415
