### ISSUE TITLE
Hydrogen canisters overpowered?

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pycoalprocessing#253]
Just place an electrolyzer and create train fuel wherever you want from just electric energy. The value of electric energy might have changed, but nevertheless it's globally available.

Are there any downsides? Bringing fuel to your trains is one of the challenges in the early game. Hydrogen canisters will trivialize this challenge.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/22458042/150562135-8e7be9cb-56d6-4e55-8d97-be270c4a89f1.png">
of course could also be belted

**Comment by oorzkws** [comment]
This is pretty punishing with the changes in dev, I'm going to consider it solved unless someone finds some major way of making it not suck.
