### ISSUE TITLE
Restrictions on assembling machines increase mall footprint

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pycoalprocessing#257]
The assembling machines seem to have a restricted [ingredient_count](https://wiki.factorio.com/Prototype/AssemblingMachine#ingredient_count). I can understand that this should balance them somehow to the automated factories, but this basically means that they are useless for building a mall. Py malls tend to be huge, if forced to use automated factories they become even bigger. Is this intended?

**Comment by oorzkws** [comment]
Yeah, it's working as intended. Automated factories are to be your main assemblers, for the most part.
