### ISSUE TITLE
Lab speed technology icons inconsistent

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pycoalprocessing#258]
With the replaced lab I'd like to see a new icon, both for the recipe/item itself, but also for the lab research speed technologies.

<img width="176" alt="image" src="https://user-images.githubusercontent.com/22458042/150572760-fdb1ba79-f354-49ce-a689-10aa4aaca628.png">
<img width="266" alt="image" src="https://user-images.githubusercontent.com/22458042/150572802-2d21beb9-7054-4b68-b7ba-d71173f5ecfa.png">
<img width="252" alt="image" src="https://user-images.githubusercontent.com/22458042/150572825-bbcea629-e951-4d59-b965-f1c5facc8a3f.png">

**Comment by oorzkws** [comment]
I've addressed the entity/item/recipe icon in bb9d3d51, but the tech icon will require a new 128px asset so that'll come later.

**Comment by oorzkws** [comment]
![image](https://user-images.githubusercontent.com/65210810/150685185-10f2709d-c99b-4d43-9e93-c878501bf9ea.png)
Resolved in 4d2c4fb8
