### ISSUE TITLE
Lab misses module slots

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pycoalprocessing#259]
To my understanding the lab module slots were removed intentionally because players could put in AL modules for higher speed.
Unfortunately this also prevents putting prod modules in labs. Gaining access to prod modules for the first time felt like a great achievement and mostly because of the free research boost granted by them. And they were achieved at ideal times, somewhere between science packs. Players will lose all of the great feeling of prod modules in labs, just because you could misuse AL modules (without any real gain, I might add). Please bring back the module slot(s).

**Comment by pyamods** [comment]
its supposed to be that way.
