### ISSUE TITLE
Request to change TURD `consumption` to something less "confusing"

### ISSUE THREAD

**Issue by hasezoey** [pyanodon/pycoalprocessing#265]
Currently, in the TURD, the upgrades list one of the things as `consumption` which by itself can be confusing, so i would request to change it to either:
- `energy consumption` (like the listed effect on efficiency modules)
- `efficiency` (like the modules themself)

(TURD = Technological Upgrade and Research Device)

PS: i dont know if the TURD is part of this mod or another, i could not quite find which of them it belongs to

**Comment by oorzkws** [comment]
This is fixed in the dev version, just not on the portal -- there are a lot of breaking changes, so the portal versions haven't been updated for some time. This will change in the future, but the ETA is uncertain, and this will likely break existing saves.
