### ISSUE TITLE
chemical-plant.ogg missing?

### ISSUE THREAD

**Issue by misho104** [pyanodon/pycoalprocessing#268]
The file `chemical-plant.ogg` seems missing in [PyCP Graphics v1.0.9](https://mods.factorio.com/mod/pycoalprocessinggraphics).

https://github.com/pyanodon/pycoalprocessing/blob/0a8a98e6cde25443f519cc0df9048d91e347044c/prototypes/buildings/chemical-plant-mk01.lua#L272

Is there any new versions of PyCP-Graphics available, or maybe this is a typo of `__base__/sound/chemical-plant.ogg`?

**Comment by oorzkws** [comment]
Hi, the mod portal versions aren't meant to be mixed with the git versions. The graphics repos are private partially to prevent reports for clearly-broken versions in dev here on github.

Just to confirm, you are mixing the git version of CoalProcessing with the portal version of graphics?
