### ISSUE TITLE
v2 not compatible with `5dim_automation`

### ISSUE THREAD

**Issue by hasezoey** [pyanodon/pycoalprocessing#326]
`pycoalprocessing` v2 is not compatible with `5dim_automation` because of error:

```txt
Error ModManager.cpp:1560: Error while running setup for entity prototype "chemical-plant" (assembling-machine): When next_upgrade is set entity mining result must not contain item product with "hidden" flag set. Mining results with no item products are allowed.
```

versions:
`pycoalprocessing`: `2.0.5`
`5dim_automation`: `1.1.1`

Note: that latest v1 version did not have a error with 5dim

Edit:

i also think https://github.com/pyanodon/pyindustry/issues/87 may be related

**Comment by notnotmelon** [comment]
pY will not support any other major overhaul mods. The only other mod with support is omni.
