### ISSUE TITLE
Sorting production chain icons

### ISSUE THREAD

**Issue by toorudez** [pyanodon/pycoalprocessing#330]
The recipe window icons do not appear to be sorted for each recipe chain. In particular, I was looking at the Niobium Plate chain, and the recipe icons are scattered throughout the recipe window. Can they be sorted similar to the ones in the Raw Ore window?

**Comment by notnotmelon** [comment]
Thanks for the report.
This is a duplicate of https://github.com/pyanodon/pybugreports/issues/358
Closing
