### ISSUE TITLE
Suggestion: Set product `show_details_in_recipe_tooltip` to `false` for complex recipes

### ISSUE THREAD

**Issue by raiguard** [pyanodon/pycoalprocessing#338]
With complex recipes such as `Fuse deuterium and helium-3`, the tooltip can become so large that it becomes very unwieldy. There exists a property [`show_details_in_recipe_tooltip`](https://lua-api.factorio.com/latest/types/ItemProductPrototype.html#show_details_in_recipe_tooltip) that will hide the product details, making the tooltip much smaller.

**Before:**

![image](https://github.com/pyanodon/pycoalprocessing/assets/3515394/c4df2e80-8c25-4095-8e2d-e1990f79f3e0)

**After:**

![image](https://github.com/pyanodon/pycoalprocessing/assets/3515394/70014178-2aec-47c0-89e4-b43c74595ade)

**EDIT:** Apologies, this probably should have been in pyfusionenergy due to the example.

**Comment by notnotmelon** [comment]
This seems to be a compatibility issue with extended descriptions. I'm thinking the better option is to update ED to automatically add this property based on product count.

**Comment by raiguard** [comment]
This was a bad example, this specific example does this due to extended descriptions, but it happens with other recipes without that mod.

![image](https://github.com/pyanodon/pycoalprocessing/assets/3515394/fcf07953-8cbf-4bd0-835f-c51558b26920)
