### ISSUE TITLE
Can't mix 2 instances of coal gas

### ISSUE THREAD

**Issue by SpaceMoehre** [pyanodon/pycoalprocessing#339]
When producing coal-gas and coal from wood and than processing the coal further, you can not mix both results of coal gases. I don't believe it is intended, because it is listed only once in the index, but the different recipes used to make the gas seem to result in to different gases.

![cannot-mix-coal-gas](https://github.com/pyanodon/pycoalprocessing/assets/34032202/9d2be8ae-b632-4d1c-b9f3-d8858cda90f2)

Here the game is signaling me, that I can't mix two different fluids.

If this IS intended, is there a way to combine them?

**Comment by kingarthur91** [comment]
It's the same gas. Like 99% sure your problem is the co2 pipe on the right.

**Comment by SpaceMoehre** [comment]
yes it was. thx for the quick answer, didnt expect an output to intake another gas
