### ISSUE TITLE
flue gas can't be burned in gas-vent

### ISSUE THREAD

**Issue by Fabboz** [pyanodon/pycoalprocessing#59]
like the title say also the recipe to 0 water don't show the gasvent icon.

**Comment by Fabboz** [comment]
i've solved the bug by making these changes but i dont know if there something wrong because loading the game some scheme are deleted.

[https://github.com/pyanodon/pyindustry/pull/7](url)

**Comment by Fabboz** [comment]
update: https://github.com/Fabboz/pyindustry/commit/57d0bc9bdccd6b217109c4bbc97e36d506588935

**Comment by kingarthur91** [comment]
well i just check it and fluegas vents just fine in the py gas vent. 

recipe to 0 water? i dont understand which one your talking about. a pic might help

**Comment by Fabboz** [comment]
i've retested with the release version and now is working but after my changes many wrong gas vent schemes are removed so my save files may be changed. 
For sure not  working at the beginning and can't replicate at the moment.

**Comment by Nexela** [comment]
Need more info on this.
