### ISSUE TITLE
actual pollution output

### ISSUE THREAD

**Issue by florianschanda** [pyanodon/pycoalprocessing#60]
Hi,

First of all your mod packs are awesome!

I was wondering about pollution. The first gas turbine and power house both show as 0.06 pollution/s and that very clearly is not right. Can that be fixed somehow? And if not could you tell me what actually influences the pollution produced by these two so I can hope to control it somehow?

Secondly, venting some gasses I assume produces pollution. Could you provide some indication on how much? E.g. if I run a methane plant for -25 would that be completely cancelled out if I just vent the gas afterwards?

I understand that there might be some limiting factors in the game that prevent you from showing the correct value.

Thanks in advance!

**Comment by kingarthur91** [comment]
they should be 0.06 pollution per minute. the pollution graph only seems to show a single decimal place so the number doesn't show up correctly on it but it is working

**Comment by florianschanda** [comment]
But that clearly doesn't seem to happen in reality. As a simple experiment you can, on a clean map, put a assembler 1 somewhere (4 pollution / minute) and far away you put a gas turbine and power house (2x 0.06 pollution/minute) and see how the map looks like after a few seconds.

There is some other factor going on that is hidden. I'd like to know what it is...

**Comment by kingarthur91** [comment]
i dont know what to tell you. there is a single line of code to set the value. power house and gas turbine are set at 0.06. same line is on the assembly machine 1 and is set to 4.

power house/gas turbine:
emissions_per_minute = 0.06,

assembly machine 1:
emissions_per_minute = 4

so i dont know what your seeing and at this point if you believe something is wrong with it then report it as a bug to the factorio devs as as everything appears to be working fine for me and theres nothing else that i can change then that line.

**Comment by florianschanda** [comment]
Just a thought: is the fuel burned in either the power house or the turbine contributing to the pollution on top of the 0.06 that is produces passively? Could this be the hidden factor?

**Comment by kingarthur91** [comment]
Not that I'm aware. I normally end up just using coke as fuel. Try using different fuels in them and see if shows a difference. 

Might also try the same on a base game boiler.
