### ISSUE TITLE
Desync with tailings pond

### ISSUE THREAD

**Issue by cpcp1998** [pyanodon/pycoalprocessing#66]
In file `scripts/tailings-pond.lua`, package-level variable `Tiles` and `tickdoubler` may cause desync problem in multiplayer games.

This bug can be reproduced by placing a large amount of `Tailings Ponds` on ground by robots and filling them with fluid `Tar`.

**Comment by kingarthur91** [comment]
pretty sure i fixed it try this https://drive.google.com/open?id=1yrWxJGBPD4nObqCY_rbI6UIOQcF_JYQg

**Comment by cpcp1998** [comment]
It works. Game no longer desyncs. Thank you for your fix.
