### ISSUE TITLE
Tailings Pond: Polluted Ground issue

### ISSUE THREAD

**Issue by Blykam** [pyanodon/pycoalprocessing#74]
The mod Pyanodons Coal Processing (1.8.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event pycoalprocessing::on_nth_tick(30)
Unknown tile name: polluted-ground
stack traceback:
	__pycoalprocessing__/scripts/tailings-pond.lua:179: in function 'handler'
	__stdlib__/stdlib/event/event.lua:335: in function 'pcall'
	__stdlib__/stdlib/event/event.lua:355: in function 'dispatch_event'
	__stdlib__/stdlib/event/event.lua:438: in function <__stdlib__/stdlib/event/event.lua:389>
stack traceback:
	[C]: in function 'set_tiles'
	__pycoalprocessing__/scripts/tailings-pond.lua:179: in function 'handler'
	__stdlib__/stdlib/event/event.lua:335: in function 'pcall'
	__stdlib__/stdlib/event/event.lua:355: in function 'dispatch_event'
	__stdlib__/stdlib/event/event.lua:438: in function <__stdlib__/stdlib/event/event.lua:389>

This error occurs, when I fill a pond with tar and let it sit there for a certain amount of time. Pls fix. I can't really play my save game anymore.

**Comment by kingarthur91** [comment]
no idea if this is still an issue. going to close this for now. if it is we can reopen the case

**Comment by Blykam** [comment]
Idk either. It was caused by the tailings pond contents (I think it was tar) reaching max capacity and then polluting the ground. Maybe an overflow error.
But it's too long ago to check.

**Comment by kingarthur91** [comment]
> Idk either. It was caused by the tailings pond contents (I think it was tar) reaching max capacity and then polluting the ground. Maybe an overflow error.
> But it's too long ago to check.

That's OK. I'll double check before our next release just in case
