### ISSUE TITLE
High pitch sound from destructive destillation column

### ISSUE THREAD

**Issue by annitya** [pyanodon/pycoalprocessing#75]
Hi!

Love your mods! The high pitch sound really hurts my ears though. Would you consider removing it?

**Comment by annitya** [comment]
If you point me in the direction of the offending file, I would be more than happy to return it to you sqeeky-free :) @pyamods

**Comment by Baughn** [comment]
Previously discussed here: https://forums.factorio.com/viewtopic.php?f=219&t=32272&start=1680#top

It's the destructive distillation column. Here's the whole sound pack treated with a low-pass filter: https://brage.info/factorio/squeal/sounds/

...which isn't ideal, but at least doesn't provoke tinnitus anymore.

**Comment by Baughn** [comment]
The specific file which offends (the most) is https://brage.info/factorio/squeal/sounds/pre-resampling/distilator.ogg

**Comment by annitya** [comment]
I tried doing some EQ myself. Pulled -12db on each of the two offending frequencies. Lost a lot of the upper clarity in the process. Not at all happy with the result, but at least it's not painful anymore. I'm hesitant to put any more effort into this until mod-maintainer responds.

**Comment by oorzkws** [comment]
Resolved in https://github.com/pyanodon/pycoalprocessinggraphics/commit/4a97e7d474e41c23d793aac9bc1d0502041943b8

**Comment by oorzkws** [comment]
> Have you released the new version? The high-pitch sound is still present.

No, it hasn't been pushed to the portal. Currently beta testing a very large set of changes.
