### ISSUE TITLE
Crystall Mine (MK2) allows all kinds of AlienLife modules

### ISSUE THREAD

**Issue by hasezoey** [pyanodon/pycoalprocessing#81]
The `Crystal mine MK 02` allows many modules from `Pyanodons AlienLife`

Versions:
Factorio: 1.1.35
PyAlienLife: 1.12.4
PyCoalProcessing: 1.9.3

![Screenshot from 2021-06-26 11-12-28](https://user-images.githubusercontent.com/10911626/123508391-7229fb80-d66f-11eb-8c03-10824ba5fe97.png)

**Comment by kingarthur91** [comment]
this is a known issue related to base game limitations
