### ISSUE TITLE
Washer at start

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#89]
Washer MK 01 is available at start, but it's not needed until Borax washing (Energy Gen 1) and Soil washing (Filtration)

Note: Where it's needed will change in other mods, but I'm pretty sure it's never needed at start.

**Comment by kingarthur91** [comment]
needs put somewhere. probably energy gen 1 if filtration has behind it somewhere

**Comment by Havvy** [comment]
Filtration is locked behind logistics science. And energy generation feels like a weird place for the washer.
Perhaps make "Borax Processing" a technology in PyCP and put the Washer and Borax related recipes there?
Which includes the boron trioxide and boric acid from logistic science pack.
