### ISSUE TITLE
Activated Carbon

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#90]
Desulfurisation tech gives you a recipe for Activated Carbon + Coal gas to Syngas, but activated carbon is unlocked with Filtration, which is down a different path in the tree.

**Comment by kingarthur91** [comment]
needs reviewed and acivated carbon moved somewhere or this recipe moved somewhere

**Comment by kingarthur91** [comment]
ive changed the desulf tech to require filtration 2 to fix that issue and removed coal processing 1 as its unneeded on a chem sci tech
