### ISSUE TITLE
Mukmoux has redundant dependency on Ralesia 

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#91]
Mukmoux already has other dependencies that require ralesia to be researched

Testing with CP + FE only

**Comment by ShadowGlass0** [comment]
Same in CP only

**Comment by ShadowGlass0** [comment]
Mukmoux pasture also requires storage tank (Fluid handling tech). As mentioned elsewhere, if Fluid handling is prereq for Energy gen 1 or Coal processing 1 (either works), it'd solve these kind of issues.

**Comment by kingarthur91** [comment]
see #118 on FH remove ralesia
