### ISSUE TITLE
Local Radar available at start

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#94]
Mods: CP, FE, Industry

Local radar is available immediately but it requires engines, which is green tech

**Comment by wesdotcool** [comment]
"Py-GasVent" is also available at the start but it is not needed until you unlock your first gasses by researching coal processing 1.

**Comment by ShadowGlass0** [comment]
[Moved to pyindustry](https://github.com/pyanodon/pyindustry/issues/15#issue-947351573)
