### ISSUE TITLE
Coal-water slurry & fluid separator

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#95]
Mods: PyCoal
Tech: Separation ("separation")
Recipes: Coal-water slurry, Coal-water slurry combustion mixture, Fluid separator

1. Coal-water slurry combustion requires Power house, which is not a prerequisite for this tech. 
2. Fluid separator requires Chemical plant, which is unlocked at Coal processing 2 (green science)
3. Coal-water slurry has no other uses in PyCoal than the combustion
4. Fluid separator is not needed for anything else before green science.

Suggestion: Make a "Fluid separation" tech, with green science, dependent on Coal Processing 2. Unlocking these 3 recipes.

Other green science recipes that can be added, which are currently in Placeholder and use Fluid Separator:
- "Split heavy oil from oleochemicals": Dependent on Mukmoux and Sulfur processing techs
- "React and split these fuels": Dependent on Filtration tech
- If both are added then the new Fluid separation tech only needs Mukmoux and Sulfur processing prerequisites. Coal processing 2 and Filtration are required for Sulfur processing

**Comment by ShadowGlass0** [comment]
Alternatively the original 3 recipes can be shoved into Coal Processing 2, "React and split these fuels" into Filtration, but "Split heavy oil from oleochemicals" would still not have a proper place.

**Comment by wesdotcool** [comment]
The Evaporator also requires a chemical plant.
The Solid Separator and Classifier both require assembly machines, but there is no dependency on Automation 1.

Suggestion: Coal Processing 1 should require Automation 1.

**Comment by ShadowGlass0** [comment]
So, instead of "Fluid separation", it can be called "Separation 2" or "Advanced separation", and have both the fluid separator and evaporator there. Also the recipes using evaporator ("tailings-dust") and their dependents ("tailings-classification", "tailings-separation").

**Comment by kingarthur91** [comment]
@ShadowGlass0 please review this issue

**Comment by ShadowGlass0** [comment]
Verified
