### ISSUE TITLE
Construction robotics only takes red science

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#96]
Mods: CP, FE, Industry

Construction robotics depends on engines (and the robots take engines to create), however the tech only requires red science to research. Should it be available at red science or green?
Additionally, it unlocks vanilla roboports which require red circuits, and it does not depend on advanced electronics

**Comment by ShadowGlass0** [comment]
[Moved to pyindustry](https://github.com/pyanodon/pyindustry/issues/16#issue-947352891)
