### ISSUE TITLE
Filtration requires wood processing 2

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pycoalprocessing#97]
Mods: CP, FE, Industry

There is nothing that wood processing 2 provides that is strictly necessary for filtration.

**Comment by ShadowGlass0** [comment]
In PyCoal only Wood Processing 2 gives a better recipe for Organic matter, which is used for Biofilm in Filtration.

**Comment by ShadowGlass0** [comment]
PyCoal only: Automation 2 can be removed as prerequisite for Filtration, as it's required for Coal Processing 2 already. (Automation 2 > Methanol Processing 1 > Coal Processing 2)
